name: Terraform Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: "00000000-0000-0000-0000-000000000000"       # substitua pelos seus valores reais
      ARM_CLIENT_SECRET: "fake-secret"
      ARM_SUBSCRIPTION_ID: "11111111-1111-1111-1111-111111111111"
      ARM_TENANT_ID: "22222222-2222-2222-2222-222222222222"
      TF_VAR_admin_password: "Lbc@123"                            # sua senha para o terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check env variables
        run: |
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
