name: Terraform Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_admin_password: ${{ secrets.ADMIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check env variables
        run: |
          echo "ARM_CLIENT_ID set? ${ARM_CLIENT_ID:+✅ YES}"
          echo "ARM_CLIENT_SECRET set? ${ARM_CLIENT_SECRET:+✅ YES}"
          echo "ARM_SUBSCRIPTION_ID set? ${ARM_SUBSCRIPTION_ID:+✅ YES}"
          echo "ARM_TENANT_ID set? ${ARM_TENANT_ID:+✅ YES}"
          echo "TF_VAR_admin_password set? ${TF_VAR_admin_password:+✅ YES}"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform

# Teste 2
