name: Terraform Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: "123e4567-e89b-12d3-a456-426614174000"
        ARM_CLIENT_SECRET: "s3cr3tV@lu3Fak3!"
        ARM_SUBSCRIPTION_ID: "98765432-1234-5678-90ab-cdef12345678"
        ARM_TENANT_ID: "abcdefab-1234-5678-90ab-abcdefabcdef"
        TF_VAR_admin_password: "FakeP@ssw0rd2025!"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check env variables
        run: |
          echo "ARM_CLIENT_ID: $ARM_CLIENT_ID"
          echo "ARM_CLIENT_SECRET: $ARM_CLIENT_SECRET"
          echo "ARM_SUBSCRIPTION_ID: $ARM_SUBSCRIPTION_ID"
          echo "ARM_TENANT_ID: $ARM_TENANT_ID"

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
